### ISSUE TITLE
Software inquiry

### ISSUE THREAD

**Issue by jennaissante** [Rogendo/Mental-health-Chatbot#1]
hello! may i please know what platform should i download to deploy the chatbot code?

**Comment by jennaissante** [comment]
I see. So the code will be put in Python right? and in order to be able to interact with the chatbot (and to be able to get the interface as you have put in the ReadME) html and css will also need to be downloaded along side with python right?

**Comment by Rogendo** [comment]
Not really, but if you want to configure the project in your computer and
be able to run it and use it, you must have python installed and configured
in your computer.
After installing Python, follow the steps in the updated readme file to
install the chatbot in your computer.
