### ISSUE TITLE
I successfully run the app, but something doesn’t look right about the chatbot

### ISSUE THREAD

**Issue by AuWhale** [Rogendo/Mental-health-Chatbot#10]
as you can see in the picture
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/48116705/7a969bb7-7703-4719-8cac-a28d5dc21346)
I asked a question to the chatbot, but it did not reply to me.
What should I do next to activate it?

**Comment by Rogendo** [comment]
The reason for this is because the chatbot was not trained using a lot of
data, so sometimes it may not respond to prompts, look for the intents.json
file to see the prompts that the chatbot was trained on, you can add more
intents and train the chatbot to respond to a particular question.

Try simple prompts like "hi", "I am depressed", " my brother died" ..etc

**Comment by digvijayyy17** [comment]
> as you can see in the picture ![image](https://private-user-images.githubusercontent.com/48116705/310730416-7a969bb7-7703-4719-8cac-a28d5dc21346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTQyNjMsIm5iZiI6MTcxMDA1Mzk2MywicGF0aCI6Ii80ODExNjcwNS8zMTA3MzA0MTYtN2E5NjliYjctNzcwMy00NzE5LThjYWMtYTI4ZDVkYzIxMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA2NTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OGUyNjFjNjJkZGE4NTk5YmI5MWQ4ZmNmMjgyMzljZTk5ZWQyNzM1NTMyMTlkZDRjZDlmMDZiYmM0MjFjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lsSYu5UrJXrs9sn3NlE_yghYXjBRhGetqwDKmvcqi6w) I asked a question to the chatbot, but it did not reply to me. What should I do next to activate it?

hey can you help me to run this program i am unable tu run the app successfully please help...

**Comment by digvijayyy17** [comment]
@AuWhale can u help me to run the app?

**Comment by its-kios09** [comment]
what error are you facing
