### ISSUE TITLE
Unable to run app.py, No Module named 'tensorflow'

### ISSUE THREAD

**Issue by imda-sitaraja** [Rogendo/Mental-health-Chatbot#11]
Hello! I had run the instructions to set up the app but am currently facing some issues. I used Anaconda to create an environment with Python 3.8.18. I have a Windows machine.

When i run the final command (flask --app app --debug run), I encounter the following error:
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/155534102/5813c229-89f4-41b5-8c57-3b51e0849453)

This occurred after the log messages for nltk_data download. 
Thanking you in advance for your assistance!

**Comment by Rogendo** [comment]
Tensorflow is not installed in your environment
To install it, run "pip install tensorflow"

**Comment by AuWhale** [comment]
After installing tensorflow, you may also need to install sentencepiece, and pytorch

**Comment by imda-sitaraja** [comment]
Hi, installed all the libraries above. Also worth noting that on top of ll these instructions, we also need to download a package from spacy using the following command:
`python -m spacy download en_core_web_sm`

The project is running now. Thank you!
