### ISSUE TITLE
needed help for installion

### ISSUE THREAD

**Issue by ASHISH14-glitch** [Rogendo/Mental-health-Chatbot#13]
after running requirements command getting this error-pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.

**Comment by ASHISH14-glitch** [comment]
ok after running how much time it takes to download data

**Comment by ASHISH14-glitch** [comment]
raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './model/eng_swa_model/'. Use `repo_type` argument if needed. -     
now getting this error
\

**Comment by its-kios09** [comment]
those are models are missing

**Comment by Pranathi-18-sudha** [comment]
Hello Sir,I am Getting the error in running flask app sir
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './model/eng_swa_model/'. Use `repo_type` argument if needed.

**Comment by Rogendo** [comment]
Did you download the models from the link provided in the readme.md?

**Comment by Pranathi-18-sudha** [comment]
Yes Sir
I Have downloaded them Both them swa_eng_model and eng_swa_model

**Comment by Rogendo** [comment]
Send a screenshot of the project tree in your environment. I need to see
the file structure and how the files look like on your end

**Comment by Pranathi-18-sudha** [comment]
![Screenshot_20240422-105219_WhatsApp.jpg](https://github.com/Rogendo/Mental-health-Chatbot/assets/123795922/ef8b00c2-7561-4ddf-b256-4e8e9b496c00)

**Comment by Rogendo** [comment]
Create a folder named model into the main project folder you cloned. In the
newly created folder, add the two downloaded models.

**Comment by Pranathi-18-sudha** [comment]
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/123795922/06ac789d-fe12-41eb-bea5-2983ec142515)

**Comment by Pranathi-18-sudha** [comment]
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/123795922/15ae3f65-4de0-455f-9d6f-86b972e260d9)
I'm getting the same error again sir

**Comment by Rogendo** [comment]
The name "models" should be in lowercase 🥲😂😂

**Comment by Pranathi-18-sudha** [comment]
Thank You for the help sir.It's running now

**Comment by Rogendo** [comment]
Glad it worked!
