### ISSUE TITLE
I have tried the code in both python 3.8 and 3.11 version but i am getting the below described issue:

### ISSUE THREAD

**Issue by Bhoomika2905** [Rogendo/Mental-health-Chatbot#6]
I have tried the code in both python 3.8 and 3.11 version but i am getting this issue :

![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/e59ed57c-eedd-47a4-81c6-dfe5d9ebee90)
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/66c30eb6-a75d-46af-bd7b-152bc61e7b58)
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/6cc3e238-9f67-4317-b08b-5dbe3486c867)

if you help me out it would be great...

**Comment by Rogendo** [comment]
Did you first try to install the dependencies by using this command

pip install -r requirements.txt??

**Comment by Bhoomika2905** [comment]
Yes, I did run the command : pip install -r requirements.txt

But i am getting this error every time.....
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/14861f27-2916-407c-8f2b-ae68f53d2fec)

I have even tried to upgrade and downgrade versions but idk the error isnt getting solved..... 

solutions tried: 
pip install keras==2.13.1
pip install tensorboard==2.13.1
pip install 'typing-extensions<4.6.0'

next error i got is: 
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/68d27297-dd43-4b6b-8296-50d38c4b879e)

solution i tried:
pip install --upgrade typing-extensions

next error i got is:
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/58ea964c-3683-4e95-a18b-3021f0fe5729)

solution i tried:
pip install 'typing-extensions<4.6.0'

repeating error:
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/87877276/3e79e043-1102-4f00-955e-9d47b7f34e14)


The errors are repeating and It will be helpful if i get some help....

**Comment by Rogendo** [comment]
I'm running the code in Ubuntu 22.04, and my python version is 3.10.12. I've installed all the packages from the requirements.txt file and got no issues, I'm still wondering what the problem on your end is. Could it be that your machine can not run the tensorflow libs? And, I've seem that you've only downloaded the 'eng_swa_model', you got to have have both models even the 'swa_eng' otherwise, you'll later get another error after you've managed to solve your environment issues.

**Comment by Rogendo** [comment]
> I have tried the code in both python 3.8 and 3.11 version but i am getting this issue :
> 
> ![image](https://private-user-images.githubusercontent.com/87877276/303146265-e59ed57c-eedd-47a4-81c6-dfe5d9ebee90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzczOTMsIm5iZiI6MTcwNzQ3NzA5MywicGF0aCI6Ii84Nzg3NzI3Ni8zMDMxNDYyNjUtZTU5ZWQ1N2MtZWVkZC00N2E0LTgxYzYtZGZlNWQ5ZWJlZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDExMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYjJjYmZkNGY4NjhlZWI2ZWE4YWYxMjE2YThlN2ViOGZlMjlmOTg0NzI2ZmQ2M2RmNmZkNTRkNGMzOTExM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpnMdEgnXSK6YFZaZhWa3xbDhYkwsIdqf2JQTG9RJ3M) ![image](https://private-user-images.githubusercontent.com/87877276/303146332-66c30eb6-a75d-46af-bd7b-152bc61e7b58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzczOTMsIm5iZiI6MTcwNzQ3NzA5MywicGF0aCI6Ii84Nzg3NzI3Ni8zMDMxNDYzMzItNjZjMzBlYjYtYTc1ZC00NmFmLWJkN2ItMTUyYmM2MWU3YjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDExMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNmMzMjk5ZGRiZWFlOWQzNzgwMjQ0NjIwNDZjMmNhNjQxN2QyYjEzYzRiMmVjNTIxYTE0MjcxYzIzNmI4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wOJw5ebaRkDWzvgGVIDLVSfpplWdv3pz-0o7L5Vx04) ![image](https://private-user-images.githubusercontent.com/87877276/303146805-6cc3e238-9f67-4317-b08b-5dbe3486c867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzczOTMsIm5iZiI6MTcwNzQ3NzA5MywicGF0aCI6Ii84Nzg3NzI3Ni8zMDMxNDY4MDUtNmNjM2UyMzgtOWY2Ny00MzE3LWIwOGItNWRiZTM0ODZjODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDExMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NzVlNjAwNWQxMTIwNGQzOTcwZmRlMzEyNWU5MmY0NzFhY2E0YjBiOGM0NmVlYzQzNzEyNzQ5ZDRkNWEyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wTl8xsaVuyzg5ny90uJ3j4W86vngdmcH7SM3AzMl92o)
> 
> if you help me out it would be great...

You could try reconfiguring the environment. First, delete the venv you have created, Then create another virtual environment. *pip list* to make sure that the virtual environment has no other libraries, sometimes you could be trying to install dependencies in your environment but the global environment of the laptop maybe messing with you, this could be the other reason if your machine has no problem with installing tensorflow and keras libs
