### ISSUE TITLE
i run python 3.10.10 

### ISSUE THREAD

**Issue by manibharathi19** [Rogendo/Mental-health-Chatbot#7]
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/106468741/7812a036-ba19-40b1-b4a0-a6749770827d)
and i run its come error 
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/106468741/e370c447-560c-4a69-a349-8fef7a50335b)
after i install  tensorflow
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/106468741/ff804fd2-aaea-443e-8292-677e7198069d)
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/106468741/1b8b5a57-4ba4-4ef7-8639-7d5ecd92b053)
can u help this plzz i have project

**Comment by Rogendo** [comment]
Your project file tree should look something like this 
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/62094358/62473186-c8ac-4d06-9ea2-650eebaa12c1)

![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/62094358/5b446247-0996-47d5-b128-95abebe4d5a1)

**Comment by Rogendo** [comment]
Download the model folder from the link [Model](https://drive.google.com/drive/folders/1ybwgK1XNG1wd8As0m9vjMdQfHmD6E9uk?usp=sharing) , then add it in the root folder where app.py file is.
