### ISSUE TITLE
I encountered some problems when configuring the environment

### ISSUE THREAD

**Issue by AuWhale** [Rogendo/Mental-health-Chatbot#8]
The python version I am using is 3.8.16. 
After executing the requirements instructions you provided, 
I tried to run the program and it prompted me that tensorflow was missing, as shown in the picture.
<img width="731" alt="71f40a0b1da3ec29c8de0d55ae3b347" src="https://github.com/Rogendo/Mental-health-Chatbot/assets/48116705/0d408e0a-75b3-43f4-8836-2b030ea1c298">
Then I installed tensorflow using pip install,
it further prompted me that the sentence piece component is missing, so I continued to install using pip.
![image](https://github.com/Rogendo/Mental-health-Chatbot/assets/48116705/8e624c66-8f95-49c0-91e7-490d63f6ed5f)
Then the error as shown in the picture appeared again. How should I solve it?

**Comment by Rogendo** [comment]
The problem is you do not have tensorflow and sentencepiece installed in your environment. To install them, run the command **pip install tensorflow sentencepiece**
