### ISSUE TITLE
Am facing issues to run app.py 

### ISSUE THREAD

**Issue by CodesCraftMan46** [Rogendo/Mental-health-Chatbot#9]

**Comment by CodesCraftMan46** [comment]
Please sir help me in this project because am a college student and didn't
know that much python but professor says its mandatory to build project in
python. Submission day is Saturday of this week.

**Comment by Rogendo** [comment]
What are your errors?

**Comment by CodesCraftMan46** [comment]
How to run it successfully sir?

**Comment by CodesCraftMan46** [comment]
It'll very helpful for me. Please help me out

**Comment by Rogendo** [comment]
Have you cloned the project yet?

**Comment by CodesCraftMan46** [comment]
No, not yet.
Can we connect on google meet please? I'll be very thankful to you. Please
help me out.

**Comment by Rogendo** [comment]
https://meet.google.com/aah-rikv-pyy

**Comment by CodesCraftMan46** [comment]
Can we connect after some time am at college? +919015282774 here's my
number. I'm from India now it's 10:33Am here. I can connect you at 5Pm. Is
it ok? Please let me know

**Comment by Rogendo** [comment]
I have other commitments to attend to at that time,  if you maybe provide your whatsApp number, we can link and organize the most favorable time.

**Comment by CodesCraftMan46** [comment]
+919015282774 here's my WhatsApp number. You can message me now. And thanku
very very much for your precious time.

**Comment by CodesCraftMan46** [comment]
Hlo sir, are you there?
